export const GET_ERRORS = 'GET_ERRORS';
export const LOG_IN= 'LOG_IN';
export const  LOGOUT ='LOGOUT'
export const GET_TODO = 'GET_TODO';
export const GET_TODOS = 'GET_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODOS = 'ADD_TODOS';
export const DELETE_TODOS = 'DELETE_TODOS';
export const DELETE_TODO = 'DELETE_TODO';
export const CLEAR_TODOS = 'CLEAR_PROFILE';
export const UPDATE_TODOS= 'UPDATE_POST';
export const PROFILE_ERRORS = 'PROFILE_ERRORS';